# Setup
title:               Dylan Marchese
tagline:             ""
description:         "Economics & Public Policy student at UChicago."
url:                 https://dylanmarchese.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Dylan Marchese
  url:               dylanmarchese.com
  email:             dylan@dylanmarchese.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
